name: submission1
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.3
  get_it: ^7.1.3
  core:
    path: core
  about:
    path: about
  search:
    path: search
  flutter_bloc: ^8.1.3
  firebase_core: ^2.24.0
  firebase_crashlytics: ^3.4.6

dev_dependencies:
  mocktail: ^1.0.1
  mockito: ^5.0.8
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.5
  test_cov_console: ^0.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - certificates/
