// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH0N5UuVPcmBHoirMb74mSvItRo637NOI',
    appId: '1:729981002287:web:d640008f202d538bcd9cda',
    messagingSenderId: '729981002287',
    projectId: 'drexapp-latihan',
    authDomain: 'drexapp-latihan.firebaseapp.com',
    storageBucket: 'drexapp-latihan.appspot.com',
    measurementId: 'G-7SYM8SRWG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq_Xl7gehBOYIqHeLf-kStYoByp22NNbg',
    appId: '1:729981002287:android:88d4762a91d426bacd9cda',
    messagingSenderId: '729981002287',
    projectId: 'drexapp-latihan',
    storageBucket: 'drexapp-latihan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMuNukClmAxoC0nX1wjPww6Umkpc71ZhI',
    appId: '1:729981002287:ios:e38c99d195ca6fdccd9cda',
    messagingSenderId: '729981002287',
    projectId: 'drexapp-latihan',
    storageBucket: 'drexapp-latihan.appspot.com',
    androidClientId: '729981002287-1k9vhdkerdg2o1gepfvlv7hgvsv2hsm5.apps.googleusercontent.com',
    iosClientId: '729981002287-kilr0v5nl3jp9di02h7l79nk5stme2rq.apps.googleusercontent.com',
    iosBundleId: 'com.example.submission1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMuNukClmAxoC0nX1wjPww6Umkpc71ZhI',
    appId: '1:729981002287:ios:3962dffa7383c908cd9cda',
    messagingSenderId: '729981002287',
    projectId: 'drexapp-latihan',
    storageBucket: 'drexapp-latihan.appspot.com',
    androidClientId: '729981002287-1k9vhdkerdg2o1gepfvlv7hgvsv2hsm5.apps.googleusercontent.com',
    iosClientId: '729981002287-ot6nm4s7cs5hovqo3rljccfasorrcic6.apps.googleusercontent.com',
    iosBundleId: 'com.example.submission1.RunnerTests',
  );
}
